{{- $labels := (include "external-services.labels" .) }}
{{- range .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name | required "Service Name is required!" }}
  namespace: {{ .namespace | default "default" }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  type: ExternalName
  externalName: {{ .URL | required "Service URL is required!" }}
{{- end }}
