{{- $name := include "external-secrets-refresher.fullname" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "0"
  labels:
    {{- include "external-secrets-refresher.labels" . | nindent 4 }}