---
image:
  repository: alpine/k8s
  tag: 1.30.2

ttlSecondsAfterFinished: 600
backoffLimit: 1
completions: 1
parallelism: 1

replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  limits:
    cpu: 250m
    memory: 128Mi
  requests:
    cpu: 250m
    memory: 128Mi

nodeSelector: {}

tolerations: []
