name: Lint and Test Charts

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.2

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.4.0

      - name: Set up helm-unittest
        run: helm plugin install https://github.com/helm-unittest/helm-unittest

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}
      
      - name: Run unit tests
        run: |
          for chart in $(ct list-changed --target-branch ${{ github.event.repository.default_branch }}); do
            if [ -d "$chart/tests/" ]; then
              helm unittest $chart
            fi
          done
  
  install-test:
    name: Test chart installability
    runs-on: ubuntu-latest
    if: ${{ needs.lint-test.outputs.charts-changed == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.2

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.4.0
      
      - name: Create kind cluster
        uses: helm/kind-action@v1.4.0

      - name: Test install charts
        run: ct install --target-branch ${{ github.event.repository.default_branch }}

      - name: Test upgrade charts
        run: ct install --target-branch ${{ github.event.repository.default_branch }} --upgrade